export const subjectsData = [
  // Second Year - Computer Science Engineering
  // Third Semester
  {
    year: 2,
    branch: "Computer Science Engineering",
    name: "Statistical Inference and Multivariate Analysis",
    link: "/materials/statistical_inference_multivariate_analysis",
    pyqLink: "/pyqs/statistical_inference_multivariate_analysis",
    worksheetLink: "/worksheets/statistical_inference_multivariate_analysis",
  },
  {
    year: 2,
    branch: "Computer Science Engineering",
    name: "Digital Logic Design",
    link: "/materials/digital_logic_design",
    pyqLink: "/pyqs/digital_logic_design",
    worksheetLink: "/worksheets/digital_logic_design",
  },
  {
    year: 2,
    branch: "Computer Science Engineering",
    name: "Mathematical Foundations of Computer Science",
    link: "/materials/mathematical_foundations_computer_science",
    pyqLink: "/pyqs/mathematical_foundations_computer_science",
    worksheetLink: "/worksheets/mathematical_foundations_computer_science",
  },
  {
    year: 2,
    branch: "Computer Science Engineering",
    name: "Object Oriented Programming Through Java",
    link: "/materials/oop_through_java",
    pyqLink: "/pyqs/oop_through_java",
    worksheetLink: "/worksheets/oop_through_java",
  },
  {
    year: 2,
    branch: "Computer Science Engineering",
    name: "Database Management Systems",
    link: "/materials/dbms",
    pyqLink: "/pyqs/dbms",
    worksheetLink: "/worksheets/dbms",
  },
  {
    year: 2,
    branch: "Computer Science Engineering",
    name: "Database Management Systems Laboratory",
    link: "/materials/dbms_lab",
    pyqLink: "/pyqs/dbms_lab",
    worksheetLink: "/worksheets/dbms_lab",
  },
  {
    year: 2,
    branch: "Computer Science Engineering",
    name: "Object Oriented Programming Through Java Laboratory",
    link: "/materials/oop_java_lab",
    pyqLink: "/pyqs/oop_java_lab",
    worksheetLink: "/worksheets/oop_java_lab",
  },
  {
    year: 2,
    branch: "Computer Science Engineering",
    name: "Data Visualization",
    link: "/materials/data_visualization",
    pyqLink: "/pyqs/data_visualization",
    worksheetLink: "/worksheets/data_visualization",
  },
  {
    year: 2,
    branch: "Computer Science Engineering",
    name: "Design Thinking",
    link: "/materials/design_thinking",
    pyqLink: "/pyqs/design_thinking",
    worksheetLink: "/worksheets/design_thinking",
  },
  {
    year: 2,
    branch: "Computer Science Engineering",
    name: "Environmental Science",
    link: "/materials/environmental_science",
    pyqLink: "/pyqs/environmental_science",
    worksheetLink: "/worksheets/environmental_science",
  },

  // Fourth Semester
  {
    year: 2,
    branch: "Computer Science Engineering",
    name: "Engineering Economics and Accountancy",
    link: "/materials/engineering_economics_accountancy",
    pyqLink: "/pyqs/engineering_economics_accountancy",
    worksheetLink: "/worksheets/engineering_economics_accountancy",
  },
  {
    year: 2,
    branch: "Computer Science Engineering",
    name: "Design and Analysis of Algorithms",
    link: "/materials/design_analysis_algorithms",
    pyqLink: "/pyqs/design_analysis_algorithms",
    worksheetLink: "/worksheets/design_analysis_algorithms",
  },
  {
    year: 2,
    branch: "Computer Science Engineering",
    name: "Operating Systems",
    link: "/materials/operating_systems",
    pyqLink: "/pyqs/operating_systems",
    worksheetLink: "/worksheets/operating_systems",
  },
  {
    year: 2,
    branch: "Computer Science Engineering",
    name: "Software Engineering",
    link: "/materials/software_engineering",
    pyqLink: "/pyqs/software_engineering",
    worksheetLink: "/worksheets/software_engineering",
  },
  {
    year: 2,
    branch: "Computer Science Engineering",
    name: "Computer Organization",
    link: "/materials/computer_organization",
    pyqLink: "/pyqs/computer_organization",
    worksheetLink: "/worksheets/computer_organization",
  },
  {
    year: 2,
    branch: "Computer Science Engineering",
    name: "Operating Systems Laboratory",
    link: "/materials/operating_systems_lab",
    pyqLink: "/pyqs/operating_systems_lab",
    worksheetLink: "/worksheets/operating_systems_lab",
  },
  {
    year: 2,
    branch: "Computer Science Engineering",
    name: "Software Engineering Laboratory",
    link: "/materials/software_engineering_lab",
    pyqLink: "/pyqs/software_engineering_lab",
    worksheetLink: "/worksheets/software_engineering_lab",
  },
  {
    year: 2,
    branch: "Computer Science Engineering",
    name: "Web Application Development",
    link: "/materials/web_application_development",
    pyqLink: "/pyqs/web_application_development",
    worksheetLink: "/worksheets/web_application_development",
  },
  {
    year: 2,
    branch: "Computer Science Engineering",
    name: "Field Project",
    link: "/materials/field_project",
    pyqLink: "/pyqs/field_project",
    worksheetLink: "/worksheets/field_project",
  },
  {
    year: 2,
    branch: "Computer Science Engineering",
    name: "Intellectual Property Rights",
    link: "/materials/intellectual_property_rights",
    pyqLink: "/pyqs/intellectual_property_rights",
    worksheetLink: "/worksheets/intellectual_property_rights",
  },
  // Second Year - Electronics and Communication Engineering
  // Third Semester
  {
    year: 2,
    branch: "Electronics and Communication Engineering",
    name: "Fourier and Complex Analysis",
    link: "/materials/fourier_complex_analysis",
    pyqLink: "/pyqs/fourier_complex_analysis",
    worksheetLink: "/worksheets/fourier_complex_analysis",
  },
  {
    year: 2,
    branch: "Electronics and Communication Engineering",
    name: "Electronic Circuit Analysis",
    link: "/materials/electronic_circuit_analysis",
    pyqLink: "/pyqs/electronic_circuit_analysis",
    worksheetLink: "/worksheets/electronic_circuit_analysis",
  },
  {
    year: 2,
    branch: "Electronics and Communication Engineering",
    name: "Switching Theory and Logic Design",
    link: "/materials/switching_theory_logic_design",
    pyqLink: "/pyqs/switching_theory_logic_design",
    worksheetLink: "/worksheets/switching_theory_logic_design",
  },
  {
    year: 2,
    branch: "Electronics and Communication Engineering",
    name: "Signals and Systems",
    link: "/materials/signals_and_systems",
    pyqLink: "/pyqs/signals_and_systems",
    worksheetLink: "/worksheets/signals_and_systems",
  },
  {
    year: 2,
    branch: "Electronics and Communication Engineering",
    name: "Probability Theory and Stochastic Processes",
    link: "/materials/probability_theory_stochastic_processes",
    pyqLink: "/pyqs/probability_theory_stochastic_processes",
    worksheetLink: "/worksheets/probability_theory_stochastic_processes",
  },
  {
    year: 2,
    branch: "Electronics and Communication Engineering",
    name: "Design Thinking",
    link: "/materials/design_thinking",
    pyqLink: "/pyqs/design_thinking",
    worksheetLink: "/worksheets/design_thinking",
  },
  {
    year: 2,
    branch: "Electronics and Communication Engineering",
    name: "Happiness and Wellbeing",
    link: "/materials/happiness_wellbeing",
    pyqLink: "/pyqs/happiness_wellbeing",
    worksheetLink: "/worksheets/happiness_wellbeing",
  },

  // Fourth Semester
  {
    year: 2,
    branch: "Electronics and Communication Engineering",
    name: "Analog Circuits",
    link: "/materials/analog_circuits",
    pyqLink: "/pyqs/analog_circuits",
    worksheetLink: "/worksheets/analog_circuits",
  },
  {
    year: 2,
    branch: "Electronics and Communication Engineering",
    name: "Analog and Digital Communications",
    link: "/materials/analog_digital_communications",
    pyqLink: "/pyqs/analog_digital_communications",
    worksheetLink: "/worksheets/analog_digital_communications",
  },
  {
    year: 2,
    branch: "Electronics and Communication Engineering",
    name: "Electromagnetic Fields and Transmission Lines",
    link: "/materials/electromagnetic_fields_transmission_lines",
    pyqLink: "/pyqs/electromagnetic_fields_transmission_lines",
    worksheetLink: "/worksheets/electromagnetic_fields_transmission_lines",
  },
  {
    year: 2,
    branch: "Electronics and Communication Engineering",
    name: "Control Systems",
    link: "/materials/control_systems",
    pyqLink: "/pyqs/control_systems",
    worksheetLink: "/worksheets/control_systems",
  },
  {
    year: 2,
    branch: "Electronics and Communication Engineering",
    name: "Computer Organization and Design",
    link: "/materials/computer_organization_design",
    pyqLink: "/pyqs/computer_organization_design",
    worksheetLink: "/worksheets/computer_organization_design",
  },
  {
    year: 2,
    branch: "Electronics and Communication Engineering",
    name: "Intellectual Property Rights",
    link: "/materials/intellectual_property_rights",
    pyqLink: "/pyqs/intellectual_property_rights",
    worksheetLink: "/worksheets/intellectual_property_rights",
  },
  {
    year: 2,
    branch: "Electronics and Communication Engineering",
    name: "Python Programming and Practice",
    link: "/materials/python_programming_practice",
    pyqLink: "/pyqs/python_programming_practice",
    worksheetLink: "/worksheets/python_programming_practice",
  },
  {
    year: 2,
    branch: "Electronics and Communication Engineering",
    name: "Field Project",
    link: "/materials/field_project",
    pyqLink: "/pyqs/field_project",
    worksheetLink: "/worksheets/field_project",
  },
  {
    year: 1,
    branch: "Computer Science Engineering",
    name: "Matrices and Calculus",
    link: " https://drive.google.com/file/d/1pnyucMz9fCW00uN7JI0hv6bNL-OheBds/view?usp=sharing",
    pyqLink: "/pyqs/matrices_and_calculus",
    worksheetLink: "https://drive.google.com/file/d/1tdrNf9_fcqOY53CNaRS1WiUU3QGotI_7/view?usp=sharing",
  },
  {
    year: 1,
    branch: "Computer Science Engineering",
    name: "Chemistry for Engineers",
    link: " https://drive.google.com/file/d/1AR2uxqo5KDsL_Qfu-led5C_FJ5XhAna0/view?usp=sharing",
    pyqLink: "/pyqs/chemistry_for_engineers",
    worksheetLink: "/worksheets/chemistry_for_engineers",
  },
  {
    year: 1,
    branch: "Computer Science Engineering",
    name: "Basic Electrical and Electronics Engineering",
    link: " https://drive.google.com/file/d/1kzeOCq06rM64Ho1ItsBDehKplUqB5p62/view?usp=sharing",
    pyqLink: "/pyqs/basic_electrical_and_electronics_engineering",
    worksheetLink: " https://drive.google.com/file/d/19HBFy66zDiGLLd2IpqOMCsQJv_hnkF8x/view?usp=sharing",
  },
  {
    year: 1,
    branch: "Computer Science Engineering",
    name: "Programming for Problem Solving",
    link: "https://drive.google.com/file/d/1USI5iGQgKUvbcigW4qgoWpUCK2gmXIhb/view?usp=sharing",
    pyqLink: "/pyqs/programming_for_problem_solving",
    worksheetLink: "/worksheets/programming_for_problem_solving",
  },
  {
    year: 1,
    branch: "Computer Science Engineering",
    name: "Engineering Drawing",
    link: " https://drive.google.com/file/d/1PbZzPaDSTWGOKjTHViBLp8JJob7UaC02/view?usp=sharing ",
    pyqLink: "/pyqs/engineering_drawing",
    worksheetLink: "/worksheets/engineering_drawing",
  },
  {
    year: 1,
    branch: "Computer Science Engineering",
    name: "Elements of Computer Science and Engineering",
    link: "/materials/elements_of_computer_science_and_engineering",
    pyqLink: "/pyqs/elements_of_computer_science_and_engineering",
    worksheetLink: "/worksheets/elements_of_computer_science_and_engineering",
  },
  {
    year: 1,
    branch: "Computer Science Engineering",
    name: "Induction Programme",
    link: "/materials/induction_programme",
    pyqLink: "/pyqs/induction_programme",
    worksheetLink: "/worksheets/induction_programme",
  },

  // Second Semester
  {
    year: 1,
    branch: "Computer Science Engineering",
    name: "Ordinary Differential Equations and Vector Calculus",
    link: " https://drive.google.com/file/d/1_p_ZTYzxiYlKgQ1x8j3kkOeEsY_O1FVd/view?usp=sharing",
    pyqLink: "/pyqs/ordinary_differential_equations_and_vector_calculus",
    worksheetLink: " https://drive.google.com/file/d/1ksyJ_zfJrpJb7abX1iQSQF84RwEKI8qj/view?usp=sharing",
  },
  {
    year: 1,
    branch: "Computer Science Engineering",
    name: "Statistical Methods for Data Analysis",
    link: " https://drive.google.com/file/d/1AMmETx6uMtZLxeLKxzC-64yA0HHcAuli/view?usp=sharing",
    pyqLink: "/pyqs/statistical_methods_for_data_analysis",
    worksheetLink: " https://drive.google.com/file/d/15Frqma45n7vAPIAipoLYne2jNHu7Hzuu/view?usp=sharing",
  },
  {
    year: 1,
    branch: "Computer Science Engineering",
    name: "English for Skill Enhancement",
    link: " https://drive.google.com/file/d/1D6GPr1BInWJJ1XAccQvCmpXYl6LFhfo-/view?usp=sharing",
    pyqLink: "/pyqs/english_for_skill_enhancement",
    worksheetLink: "/worksheets/english_for_skill_enhancement",
  },
  {
    year: 1,
    branch: "Computer Science Engineering",
    name: "Data Structures",
    link: " https://drive.google.com/file/d/1NhQVkorNIb3qRzm003wnlcNwxYwpU0N4/view?usp=sharing",
    pyqLink: "/pyqs/data_structures",
    worksheetLink: " https://drive.google.com/file/d/1s-k6mJG9vZv5nSTpkpYov-K7OQ-mjTAL/view?usp=sharing ",
  },
  {
    year: 1,
    branch: "Computer Science Engineering",
    name: "Applied Physics",
    link: " https://drive.google.com/file/d/1nURcDilgN-zfPJLr6L0OkCRCMhBQZslM/view?usp=sharing",
    pyqLink: "/pyqs/applied_physics",
    worksheetLink: " https://drive.google.com/file/d/1oby3WXcK_6cw-1rnSKrrO3-LWCnYzHK6/view?usp=sharing ",
  },
  {
    year: 1,
    branch: "Computer Science Engineering",
    name: "Engineering and IT Workshop",
    link: "/materials/engineering_and_it_workshop",
    pyqLink: "/pyqs/engineering_and_it_workshop",
    worksheetLink: "/worksheets/engineering_and_it_workshop",
  },
  {
    year: 1,
    branch: "Computer Science Engineering",
    name: "Happiness and Wellbeing",
    link: "/materials/happiness_and_wellbeing",
    pyqLink: "/pyqs/happiness_and_wellbeing",
    worksheetLink: "/worksheets/happiness_and_wellbeing",
  },
  // First Year - Electronics and Communication Engineering
  // First Semester
  {
    year: 1,
    branch: "Electronics and Communication Engineering",
    name: "Matrices and Calculus",
    link: " https://drive.google.com/file/d/1pnyucMz9fCW00uN7JI0hv6bNL-OheBds/view?usp=sharing ",
    pyqLink: "/pyqs/matrices_and_calculus",
    worksheetLink: " https://drive.google.com/file/d/1tdrNf9_fcqOY53CNaRS1WiUU3QGotI_7/view?usp=sharing ",
  },
  {
    year: 1,
    branch: "Electronics and Communication Engineering",
    name: "Applied Physics",
    link: " https://drive.google.com/file/d/1nURcDilgN-zfPJLr6L0OkCRCMhBQZslM/view?usp=sharing ",
    pyqLink: "/pyqs/applied_physics",
    worksheetLink: " https://drive.google.com/file/d/1oby3WXcK_6cw-1rnSKrrO3-LWCnYzHK6/view?usp=sharing ",
  },
  {
    year: 1,
    branch: "Electronics and Communication Engineering",
    name: "Programming for Problem Solving",
    link: " https://drive.google.com/file/d/1USI5iGQgKUvbcigW4qgoWpUCK2gmXIhb/view?usp=sharing ",
    pyqLink: "/pyqs/programming_for_problem_solving",
    worksheetLink: "/worksheets/programming_for_problem_solving",
  },
  {
    year: 1,
    branch: "Electronics and Communication Engineering",
    name: "English for Skill Enhancement",
    link: " https://drive.google.com/file/d/1D6GPr1BInWJJ1XAccQvCmpXYl6LFhfo-/view?usp=sharing ",
    pyqLink: "/pyqs/english_for_skill_enhancement",
    worksheetLink: "/worksheets/english_for_skill_enhancement",
  },
  {
    year: 1,
    branch: "Electronics and Communication Engineering",
    name: "Electrical Circuits",
    link: "/materials/electrical_circuits",
    pyqLink: "/pyqs/electrical_circuits",
    worksheetLink: "/worksheets/electrical_circuits",
  },
  {
    year: 1,
    branch: "Electronics and Communication Engineering",
    name: "Engineering Workshop",
    link: "/materials/engineering_workshop",
    pyqLink: "/pyqs/engineering_workshop",
    worksheetLink: "/worksheets/engineering_workshop",
  },
  {
    year: 1,
    branch: "Electronics and Communication Engineering",
    name: "Induction Programme",
    link: "/materials/induction_programme",
    pyqLink: "/pyqs/induction_programme",
    worksheetLink: "/worksheets/induction_programme",
  },

  // Second Semester
  {
    year: 1,
    branch: "Electronics and Communication Engineering",
    name: "Ordinary Differential Equations and Vector Calculus",
    link: " https://drive.google.com/file/d/1_p_ZTYzxiYlKgQ1x8j3kkOeEsY_O1FVd/view?usp=sharing ",
    pyqLink: "/pyqs/ordinary_differential_equations_and_vector_calculus",
    worksheetLink: " https://drive.google.com/file/d/1ksyJ_zfJrpJb7abX1iQSQF84RwEKI8qj/view?usp=sharing ",
  },
  {
    year: 1,
    branch: "Electronics and Communication Engineering",
    name: "Chemistry for Engineers",
    link: " https://drive.google.com/file/d/1AR2uxqo5KDsL_Qfu-led5C_FJ5XhAna0/view?usp=sharing ",
    pyqLink: "/pyqs/chemistry_for_engineers",
    worksheetLink: "/worksheets/chemistry_for_engineers",
  },
  {
    year: 1,
    branch: "Electronics and Communication Engineering",
    name: "Basic Electrical Engineering",
    link: "/materials/basic_electrical_engineering",
    pyqLink: "/pyqs/basic_electrical_engineering",
    worksheetLink: "/worksheets/basic_electrical_engineering",
  },
  {
    year: 1,
    branch: "Electronics and Communication Engineering",
    name: "Electronic Devices and Circuits",
    link: " https://drive.google.com/file/d/18f3BWdzZgsdW2sSeJ2MEbuazC9y6s94n/view?usp=sharing",
    pyqLink: "/pyqs/electronic_devices_and_circuits",
    worksheetLink: "/worksheets/electronic_devices_and_circuits",
  },
  {
    year: 1,
    branch: "Electronics and Communication Engineering",
    name: "Data Structures",
    link: " https://drive.google.com/file/d/1NhQVkorNIb3qRzm003wnlcNwxYwpU0N4/view?usp=sharing ",
    pyqLink: "/pyqs/data_structures",
    worksheetLink: " https://drive.google.com/file/d/1s-k6mJG9vZv5nSTpkpYov-K7OQ-mjTAL/view?usp=sharing ",
  },
  {
    year: 1,
    branch: "Electronics and Communication Engineering",
    name: "Environmental Science",
    link: "/materials/environmental_science",
    pyqLink: "/pyqs/environmental_science",
    worksheetLink: "/worksheets/environmental_science",
  },
];
